name: CD

on:
  push:
    tags:
      - '*'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Create GitHub release & Attach artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: ${{ contains(steps.version.outputs.tag, 'M') }}
          name: ${{ steps.version.outputs.tag }}
          tag_name: ${{ steps.version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: sbt "project grpc" clean +ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.SONA_PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.SONA_PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONA_PASS }}
          SONATYPE_USERNAME: ${{ secrets.SONA_USER }}
